# Generated by Django 4.0.3 on 2022-03-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polaroidapp', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
