# Generated by Django 4.0.3 on 2022-03-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polaroidapp', '0004_image_likes_delete_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(default='profiles/13.jpg', null=True, upload_to='profiles/'),
        ),
    ]
